version: '3'
services:
  test:
    image: jmorin98/test
    hostname: test
    environment:
      NODE_ID: test
      LOGS_PATH: /logs
      NODE_PORT: 5000
    
    volumes:
      - /home/jmorin/test/logs:/app/data/logs
    networks:
      - proto_net
    ports:
      - 4999:5000
      
  lb_generic_z_0:
    image: jmorin98/loadbalancer
    hostname: lb_generic_z_0
    environment:

      NODE_ID: lb_generic_z_0
      ALGORITHM: RR
      IP: '127.0.0.1'
      PUBLIC_PORT: 5454
      DOCKER_PORT: 5000
      MODE: DOCKER 
      PRESENTATION: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
    # build:
    #   context: ./lb_generic
    #   dockerfile: ./Dockerfile
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5454:5000

  clustering_0:
    image: jmorin98/clustering
    hostname: clustering_0
    environment:
      NODE_ID: conteo_0
      IP: '127.0.0.1'
      PUBLIC_PORT: 5001
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_z_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5454
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5001:5000
networks:
  proto_net:
