version: '3'
services:
  test:
    image: jmorin98/test
    hostname: test
    environment:
      NODE_ID: lb_generic_esp_1
      LOGS_PATH: /logs
      NODE_PORT: 5000
    
    volumes:
      - /home/jmorin/logs:/app/data/logs
    networks:
      - proto_net
    ports:
      - 4999:5000
      
  lb_generic_z_0:
    image: jmorin98/loadbalancer
    hostname: lb_generic_z_0
    environment:

      NODE_ID: lb_generic_z_0
      ALGORITHM: RR
      IP: '127.0.0.1'
      PUBLIC_PORT: 5454
      DOCKER_PORT: 5000
      MODE: DOCKER 
      PRESENTATION: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs
    # build:
    #   context: ./lb_generic
    #   dockerfile: ./Dockerfile
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5454:5000

  lb_generic_tem_0:
    image: jmorin98/loadbalancer
    hostname: lb_generic_tem_0
    environment:
      NODE_ID: lb_generic_tem_0
      IP: '127.0.0.1'
      PUBLIC_PORT: 5001
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_z_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5454
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5001:5000
  
  lb_generic_tem_1:
    image: jmorin98/loadbalancer
    hostname: lb_generic_tem_1
    environment:
      NODE_ID: lb_generic_tem_1
      IP: '127.0.0.1'
      PUBLIC_PORT: 5002
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_z_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5454
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5002:5000
  
  lb_generic_tem_2:
    image: jmorin98/loadbalancer
    hostname: lb_generic_tem_2
    environment:
      NODE_ID: lb_generic_tem_2
      IP: '127.0.0.1'
      PUBLIC_PORT: 5003
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_z_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5454
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5003:5000
  
  lb_generic_tem_3:
    image: jmorin98/loadbalancer
    hostname: lb_generic_tem_3
    environment:
      NODE_ID: lb_generic_tem_3
      IP: '127.0.0.1'
      PUBLIC_PORT: 5004
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_z_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5454
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5004:5000
  
  lb_generic_tem_4:
    image: jmorin98/loadbalancer
    hostname: lb_generic_tem_4
    environment:
      NODE_ID: lb_generic_tem_4
      IP: '127.0.0.1'
      PUBLIC_PORT: 5005
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_z_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5454
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5005:5000
  
  correlation_0:
    image: jmorin98/correlation
    hostname: correlation_0
    environment:
      NODE_ID: correlation_0
      IP: '127.0.0.1'
      PUBLIC_PORT: 5006
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_tem_0
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5001
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5006:5000
  
  correlation_1:
    image: jmorin98/correlation
    hostname: correlation_1
    environment:
      NODE_ID: correlation_1
      IP: '127.0.0.1'
      PUBLIC_PORT: 5007
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_tem_1
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5002
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5007:5000
  
  correlation_2:
    image: jmorin98/correlation
    hostname: correlation_2
    environment:
      NODE_ID: correlation_2
      IP: '127.0.0.1'
      PUBLIC_PORT: 5008
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_tem_2
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5003
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5008:5000
  
  correlation_3:
    image: jmorin98/correlation
    hostname: correlation_3
    environment:
      NODE_ID: correlation_3
      IP: '127.0.0.1'
      PUBLIC_PORT: 5009
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_tem_2
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5004
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5009:5000

  correlation_4:
    image: jmorin98/correlation
    hostname: correlation_4
    environment:
      NODE_ID: correlation_4
      IP: '127.0.0.1'
      PUBLIC_PORT: 5010
      DOCKER_PORT: 5000
      MODE: DOCKER
      SEND: 0
      SOURCE_PATH: /data
      LOGS_PATH: /logs

      NODE_ID_MANAGER: lb_generic_tem_2
      IP_MANAGER: '127.0.0.1'
      PUBILC_PORT_MANAGER: 5005
      DOCKER_PORT_MANAGER: 5000
    volumes:
      - /home/jmorin/test/:/app/data/
      - /home/jmorin/test/logs/:/app/data/logs
    networks:
      - proto_net
    ports:
      - 5010:5000

networks:
  proto_net: